#!/usr/bin/env python3
"""Generate or verify adapter metadata against its plugin manifest."""
import argparse
import json
from pathlib import Path
import re
import subprocess
import sys
import tomllib

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = "computer-mcp-plugin.toml"
GENERATED = "Sources/CodexAdapter/CodexAdapterBuildInfo.swift"


def parse(value):
    if not isinstance(value, str) or not re.fullmatch(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", value):
        raise ValueError("Expected a release MAJOR.MINOR.PATCH version")
    return tuple(map(int, value.split(".")))


def read(root):
    value = tomllib.loads((root / MANIFEST).read_text())["version"]
    parse(value)
    return value


def generated(value):
    return f'''// Generated by Scripts/version.py from computer-mcp-plugin.toml.
package enum CodexAdapterBuildInfo {{
  package static let version = "{value}"
}}
'''


def git(root, *arguments):
    return subprocess.run(["git", *arguments], cwd=root, capture_output=True, text=True, timeout=30, check=True).stdout.strip()


def check(root, binary=None, base=None, tag=None):
    value = read(root)
    if (root / GENERATED).read_text() != generated(value):
        raise ValueError("Adapter metadata differs from manifest; run Scripts/version.py generate")
    if binary:
        result = subprocess.run([str(binary.resolve()), "--version"], capture_output=True, text=True, timeout=10, check=True)
        if result.stdout.strip() != value:
            raise ValueError("Actual adapter version differs from manifest")
    if base:
        previous = tomllib.loads(git(root, "show", f"{base}:{MANIFEST}"))["version"]
        if parse(value) < parse(previous):
            raise ValueError("Plugin version must not move backwards from the base commit")
    if tag:
        if tag != "v" + value:
            raise ValueError("Release tag differs from the manifest version")
        if git(root, "rev-parse", f"refs/tags/{tag}^{{commit}}") != git(root, "rev-parse", "HEAD"):
            raise ValueError("Release tag does not identify the checked commit")
    return value


def next_version(current, kind):
    major, minor, patch = parse(current)
    if kind == "fix":
        return f"{major}.{minor}.{patch + 1}"
    if kind == "feature" or major == 0:
        return f"{major}.{minor + 1}.0"
    return f"{major + 1}.0.0"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    commands = parser.add_subparsers(dest="command", required=True)
    verify = commands.add_parser("check")
    verify.add_argument("--binary", type=Path)
    verify.add_argument("--base", help="Base commit whose manifest must not have a newer version")
    verify.add_argument("--tag", help="Existing formal tag to verify against the manifest and HEAD")
    commands.add_parser("generate")
    update = commands.add_parser("update")
    update.add_argument("--kind", required=True, choices=("fix", "feature", "breaking"))
    update.add_argument("--reason", required=True)
    args = parser.parse_args()
    root = args.root.resolve()
    current = read(root)
    if args.command == "check":
        print(json.dumps({"status": "passed", "version": check(root, args.binary, args.base, args.tag)}))
        return
    if args.command == "generate":
        (root / GENERATED).write_text(generated(current))
        return
    if not args.reason.strip():
        raise ValueError("An upgrade rationale is required")
    target = next_version(current, args.kind)
    existing = subprocess.run(["git", "tag", "--list", "v" + target], cwd=root, capture_output=True, text=True, check=True).stdout.strip()
    if existing:
        raise ValueError("The formal version already exists and is immutable")
    text = (root / MANIFEST).read_text()
    # Only the top-level manifest owns the plugin version.
    top, separator, tables = text.partition("\n[")
    top, count = re.subn(r"(?m)^version\s*=\s*(['\"])[^'\"]+\1\s*$", f'version = "{target}"', top)
    if count != 1:
        raise ValueError("Expected exactly one top-level manifest version")
    result = top + separator + tables
    if tomllib.loads(result)["version"] != target:
        raise ValueError("Manifest update failed validation")
    (root / MANIFEST).write_text(result)
    (root / GENERATED).write_text(generated(target))
    print(json.dumps({"component": "plugin-codex", "previous": current, "version": target, "kind": args.kind, "reason": args.reason}))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, KeyError, subprocess.SubprocessError) as error:
        print(f"Plugin version check failed: {error}", file=sys.stderr)
        sys.exit(1)
